#!/usr/bin/env bash


ln -sf ~/callum/dotfiles/.bashrc ~/.bashrc
ln -sf ~/callum/dotfiles/.bin ~/.bin
ln -sf ~/callum/dotfiles/.ssh ~/.ssh
ln -sf ~/callum/dotfiles/.vimrc ~/.vimrc
ln -sf ~/callum/dotfiles/.zshrc ~/.zshrc
ln -sf ~/callum/dotfiles/.tmux ~/.tmux
ln -sf ~/callum/dotfiles/.tmux.conf ~/.tmux.conf
