#!/usr/bin/env bash


ln -s ~/callum/dotfiles/.bashrc ~/.bashrc
ln -s ~/callum/dotfiles/.bin ~/.bin
ln -s ~/callum/dotfiles/.ssh ~/.ssh
ln -s ~/callum/dotfiles/.vimrc ~/.vimrc
ln -s ~/callum/dotfiles/.zshrc ~/.zshrc
ln -s ~/callum/dotfiles/.tmux ~/.tmux
ln -s ~/callum/dotfiles/.tmux.conf ~/.tmux.conf
