#!/usr/bin/env bash


ln -sf /data//callum/dotfiles/.bashrc ~/.bashrc
ln -sf /data/callum/dotfiles/.bin ~/.bin
#ln -sf /data/callum/dotfiles/ssh ~/.ssh
ln -sf /data/callum/dotfiles/.vimrc ~/.vimrc
#ln -sf /data/callum/zshrc ~/.zshrc
ln -sf /data/callum/dotfiles/.tmux ~/.tmux
ln -sf /data/callum/dotfiles/.tmux.conf ~/.tmux.conf
