#!/usr/bin/env bash

while getopts ":hrl" opt; do
  case ${opt} in
    h )
      echo "Usage:"
      echo "    pip -h                      Display this help message."
      echo "    pip install                 Install a Python package."
      exit 0
      ;;
    r )
	echo "remote backup"
	echo "using Rclone to backup the Desktop and Script directories to kclonedrive"
	rclone copy /Users/callum/callum/ kclone:/osxbackups/callum/ -P
	;;
    l )
	echo "local backups"
	if [ -d "/Volumes/PATRIOT" ] 
	then
	    echo "Backing up to PATRIOT"
	    echo "backing up Thesis"
	    rclone sync kclone:/PHD/THESIS_WORD /Volumes/PATRIOT/THESIS/THESIS_WORD -P
	    rclone sync kclone:/PHD/THESIS_LATEX /Volumes/PATRIOT/THESIS/THESIS_LATEX -P
	    echo "backing up endnote"
	    rsync  -auHEP   --exclude={"*/.DS_STORE","*/.git","*/.idea","*/.ipynb_checkpoints","*/__pycache__"} /Users/callum/Documents/ /Volumes/PATRIOT/ 
	    echo "callum scripts directory"
	    rsync  -auHEP   --exclude={"*i.DS_STORE","*/.git","*/.idea","*/.ipynb_checkpoints","*/__pycache__"} ~/callum/ /Volumes/PATRIOT/ 
	    
	fi
	;;
    \? )
      echo "Invalid Option: -$OPTARG" 1>&2
      exit 1
      ;;
  esac
done
shift $((OPTIND -1))
